# Generated by Django 2.2.28 on 2023-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holderName', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('cvv', models.IntegerField()),
                ('expiration', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDatetime', models.DateTimeField()),
                ('status', models.CharField(max_length=256)),
                ('creditCard', models.ManyToManyField(related_name='payment_creditCard', to='payments.CreditCard')),
                ('subscription', models.ManyToManyField(related_name='payment_subscription', to='subscription.Subscription')),
            ],
        ),
    ]
