# Generated by Django 2.2.28 on 2023-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
