# Generated by Django 2.2.28 on 2023-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230517_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='character',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='character_rules', to='home.CharacterRule'),
        ),
    ]
