# Generated by Django 2.2.28 on 2023-05-17 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20230517_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeX', models.IntegerField()),
                ('sizeY', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('gameTimer', models.IntegerField(blank=True, null=True)),
                ('timerPerMove', models.IntegerField(blank=True, null=True)),
                ('gameSetupTime', models.IntegerField(blank=True, null=True)),
                ('board', models.ManyToManyField(blank=True, related_name='chessgame_board', to='home.Board')),
                ('characters', models.ManyToManyField(blank=True, related_name='chessgame_characters', to='home.Character')),
                ('owner', models.ManyToManyField(blank=True, related_name='chessgame_owner', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='chessgame_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('gameColor', models.IntegerField()),
                ('game', models.ManyToManyField(related_name='gameinvitation_game', to='home.ChessGame')),
                ('invitedPlayer', models.ManyToManyField(related_name='gameinvitation_invitedPlayer', to=settings.AUTH_USER_MODEL)),
                ('sourceInvitation', models.ManyToManyField(related_name='gameinvitation_sourceInvitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('character', models.ManyToManyField(blank=True, related_name='boardspot_character', to='home.Character')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='spots',
            field=models.ManyToManyField(blank=True, related_name='board_spots', to='home.BoardSpot'),
        ),
    ]
