# Generated by Django 2.2.28 on 2023-05-17 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20230517_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('sourceRequest', models.ManyToManyField(related_name='friendrequest_sourceRequest', to=settings.AUTH_USER_MODEL)),
                ('targetRequest', models.ManyToManyField(related_name='friendrequest_targetRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
