# Generated by Django 2.2.28 on 2023-05-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
