# Generated by Django 2.2.28 on 2023-05-17 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230517_1330'),
        ('subscription', '0001_initial'),
        ('users', '0006_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceptedPrivacyPolicy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='acceptedTerms',
            field=models.BooleanField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favoriteCharacters',
            field=models.ManyToManyField(blank=True, related_name='user_favoriteCharacters', to='home.Character'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='user_subscription', to='subscription.Subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
