# Generated by Django 2.2.28 on 2023-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0007_auto_20230517_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversations',
            field=models.ManyToManyField(blank=True, related_name='user_conversations', to='chat.Chat'),
        ),
    ]
