# Generated by Django 2.2.28 on 2023-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('notification', '0001_initial'),
        ('users', '0008_user_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creditCards',
            field=models.ManyToManyField(blank=True, related_name='user_creditCards', to='payments.CreditCard'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='user_notifications', to='notification.Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='user_payments', to='payments.Payment'),
        ),
    ]
